# Generated by Django 3.1.4 on 2021-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210803_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
